const motivationalSentences = [
    "Believe in yourself.",
    "Keep pushing forward.",
    "Success is a journey, not a destination.",
    "You are capable of amazing things.",
    "Embrace the challenges.",
    "Dream big, work hard.",
    "Your attitude determines your direction.",
    "Failure is the first step to success.",
    "Stay focused and never give up.",
    "Chase your goals relentlessly.",
    "You have the power to change your life.",
    "Every day is a fresh start.",
    "Make today count.",
    "Hard work pays off.",
    "Stay positive and stay fighting.",
    "Your potential is limitless.",
    "Set goals, take action, achieve greatness.",
    "Believe in your abilities.",
    "You are stronger than you think.",
    "Success begins with a single step.",
    "Don't wait for opportunity, create it.",
    "Stay hungry, stay foolish.",
    "The only limit is your imagination.",
    "You are the author of your own story.",
    "Success is the sum of small efforts.",
    "Never stop learning.",
    "Push through the pain, and you'll find the gain.",
    "Your future is created by what you do today.",
    "Make it happen.",
    "Strive for progress, not perfection.",
    "Great things take time.",
    "You are the master of your fate.",
    "Keep your eyes on the prize.",
    "Every setback is a setup for a comeback.",
    "Stay positive, stay fighting, stay brave, stay ambitious.",
    "Success is not an accident, it's a choice.",
    "Focus on the journey, not the destination.",
    "Keep your head up, and your heart strong.",
    "You have the potential to change the world.",
    "The best time to start is now.",
    "Hard work beats talent when talent doesn't work hard.",
    "Believe you can, and you're halfway there.",
    "Your future is bright.",
    "You are a force to be reckoned with.",
    "Dreams don't work unless you do.",
    "The only way to do great work is to love what you do.",
    "Every day is a second chance.",
    "Life is tough, but so are you.",
    "Keep going until you're proud.",
    "Success is the result of preparation and hard work.",
    "You are stronger than your excuses.",
    "In the middle of every difficulty lies opportunity.",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder you work, the luckier you get.",
    "The secret to getting ahead is getting started.",
    "Do what you can with all you have, wherever you are.",
    "Believe in the power of your dreams.",
    "Never give up on something you can't go a day without thinking about.",
    "Dream it. Believe it. Achieve it.",
    "Difficulties in life are intended to make us better, not bitter.",
    "Your success is my success.",
    "Let your faith be bigger than your fears.",
    "You are one decision away from a totally different life.",
    "Doubt kills more dreams than failure ever will.",
    "You are a diamond; they can't break you.",
    "Keep moving forward, even if it's just one step at a time.",
    "Rise up, start fresh. See the bright opportunity in each new day.",
    "The only way to predict the future is to create it.",
    "You are what you believe yourself to be.",
    "Every morning brings new potential.",
    "Your only limit is your mind.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Success is not just about making money. It's about making a difference.",
    "You are the CEO of your life. Start making executive decisions.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Chase your dreams until they become reality.",
    "The greatest pleasure in life is doing what people say you cannot do.",
    "You are the architect of your destiny.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Your dreams are valid.",
    "Your journey has just begun; enjoy the ride.",
    "Focus on the step in front of you, not the whole staircase.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited; don't waste it living someone else's life.",
    "Every accomplishment starts with the decision to try.",
    "You are the author of your own story, so make it a bestseller.",
    "You are capable of more than you know.",
    "Every morning you have two choices: continue to sleep with your dreams or wake up and chase them.",
    "Your life is your message to the world; make it inspiring.",
    "The only thing standing between you and your goal is the story you keep telling yourself."
  ];
